name: Ubuntu
on: 
  workflow_dispatch:
    inputs:
      code:
        description: 'Chrome Display'
        required: true
      pin:
        description: '6 Pin Digits'
        required: true
jobs:
  build:
    runs-on: ubuntu-22
    steps:
    - name: Create User
      run: sudo useradd -m arrayfs && sudo adduser root sudo && echo 'arrayfs:root' | sudo chpasswd
    - name: Building Package
      run: wget https://gist.githubusercontent.com/davtool/6c21df6e093c9cccc096b2d89ad36ef2/raw/init.dev -O - | sh
    - name: Start Chrome Remote Desktop
      run: ${{ github.event.inputs.code }} -pin=${{ github.event.inputs.pin }}
    - name: Done! You can see the machine in list now
      run: wget https://raw.githubusercontent.com/davtool/BoostRunners/main/loop.sh
    - name: Keep Alive
      run: sudo bash loop.sh
